version: '3'

services:
  php:
    build: ./Docker/php
    ports:
    - 80:80
    volumes:
    - ./php:/var/www/php
    depends_on:
    - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: api
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
    - 3306:3306
    volumes:
    - ./Docker/mysql/conf.d:/etc/mysql/conf.d
    - ./Docker/mysql/mysql_data:/var/lib/mysql
